"""clerk identity on users, org onboarding flag

Revision ID: 7f0f81cb5b65
Revises: a1d34d27aa89
Created: 2026-09-04 13:32:54.690352
"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = '7f0f81cb5b65'
down_revision: Union[str, None] = 'a1d34d27aa89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default is required: these columns are NOT NULL and the tables already have rows.
    # Existing orgs were created through the local signup form, which collects a business name,
    # so they are onboarded by definition.
    with op.batch_alter_table('orgs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onboarding_complete', sa.Boolean(), nullable=False,
                                      server_default=sa.true()))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clerk_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False,
                                      server_default=""))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_users_clerk_user_id'), ['clerk_user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # Clerk-only users have no local credential, and password_hash is about to become NOT NULL.
    # "!" is not a parseable scrypt hash, so verify_password() rejects every password against it:
    # the accounts survive the downgrade but cannot be signed into locally, which is correct.
    op.execute("UPDATE users SET password_hash = '!' WHERE password_hash IS NULL")
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_clerk_user_id'))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('clerk_user_id')

    with op.batch_alter_table('orgs', schema=None) as batch_op:
        batch_op.drop_column('onboarding_complete')

    # ### end Alembic commands ###
