"""initial schema

Revision ID: c62604634d53
Revises: 
Created: 2026-09-04 12:40:57.442710
"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = 'c62604634d53'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_attempts_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_key'), ['key'], unique=False)

    op.create_table('orgs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('legal_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reply_to_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('support_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plan', sa.Enum('TRIAL', 'STARTER', 'GROWTH', 'SCALE', name='plan'), nullable=False),
    sa.Column('subscription_status', sa.Enum('TRIALING', 'ACTIVE', 'PAST_DUE', 'CANCELLED', name='subscriptionstatus'), nullable=False),
    sa.Column('trial_ends_on', sa.Date(), nullable=True),
    sa.Column('rzp_subscription_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rzp_customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rzp_key_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rzp_key_secret_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rzp_webhook_secret_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('agent_enabled', sa.Boolean(), nullable=False),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.Column('llm_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orgs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orgs_slug'), ['slug'], unique=True)

    op.create_table('audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('event', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('actor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prev', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_event'), ['event'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_seq'), ['seq'], unique=False)

    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('do_not_contact', sa.Boolean(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'external_id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_org_id'), ['org_id'], unique=False)

    op.create_table('risk_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('fitted_at', sa.DateTime(), nullable=False),
    sa.Column('weights_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('train_rows', sa.Integer(), nullable=False),
    sa.Column('holdout_rows', sa.Integer(), nullable=False),
    sa.Column('positives', sa.Integer(), nullable=False),
    sa.Column('precision', sa.Float(), nullable=False),
    sa.Column('recall', sa.Float(), nullable=False),
    sa.Column('f1', sa.Float(), nullable=False),
    sa.Column('base_rate', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_models_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_models_fitted_at'), ['fitted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_models_org_id'), ['org_id'], unique=False)

    op.create_table('run_locks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('holder', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run_locks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_locks_org_id'), ['org_id'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'MEMBER', name='role'), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_org_id'), ['org_id'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('amount_paid_paise', sa.Integer(), nullable=False),
    sa.Column('issued_on', sa.Date(), nullable=False),
    sa.Column('due_on', sa.Date(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_count', sa.Integer(), nullable=False),
    sa.Column('last_contact_on', sa.Date(), nullable=True),
    sa.Column('next_action_on', sa.Date(), nullable=True),
    sa.Column('promised_pay_on', sa.Date(), nullable=True),
    sa.Column('inbound_pending', sa.Boolean(), nullable=False),
    sa.Column('last_inbound_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dispute_open', sa.Boolean(), nullable=False),
    sa.Column('hardship_flagged', sa.Boolean(), nullable=False),
    sa.Column('cease_requested', sa.Boolean(), nullable=False),
    sa.Column('escalation_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stop_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('discount_pct_offered', sa.Float(), nullable=False),
    sa.Column('settlement_amount_paise', sa.Integer(), nullable=True),
    sa.Column('payment_link_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payment_link_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('plan_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'number')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_due_on'), ['due_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_next_action_on'), ['next_action_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_status'), ['status'], unique=False)

    op.create_table('policy_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('contact_window_start_hour', sa.Integer(), nullable=False),
    sa.Column('contact_window_end_hour', sa.Integer(), nullable=False),
    sa.Column('min_gap_days_between_contacts', sa.Integer(), nullable=False),
    sa.Column('max_contacts_per_invoice', sa.Integer(), nullable=False),
    sa.Column('max_early_settlement_discount_pct', sa.Float(), nullable=False),
    sa.Column('min_days_overdue_for_discount', sa.Integer(), nullable=False),
    sa.Column('max_installments', sa.Integer(), nullable=False),
    sa.Column('max_plan_interval_days', sa.Integer(), nullable=False),
    sa.Column('min_first_installment_pct', sa.Float(), nullable=False),
    sa.Column('max_payment_link_expiry_days', sa.Integer(), nullable=False),
    sa.Column('min_partial_payment_pct', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policy_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_settings_org_id'), ['org_id'], unique=True)

    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('purpose', sa.Enum('VERIFY_EMAIL', 'PASSWORD_RESET', 'INVITE', name='tokenpurpose'), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'MEMBER', name='role'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tokens_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tokens_purpose'), ['purpose'], unique=False)
        batch_op.create_index(batch_op.f('ix_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_org_id'), ['org_id'], unique=False)

    op.create_table('outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('to_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_APPROVAL', 'QUEUED', 'SENT', 'FAILED', 'REJECTED', name='outboxstatus'), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rationale', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('decided_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outbox', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outbox_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_status'), ['status'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('external_payment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'external_payment_id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_org_id'), ['org_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_org_id'))
        batch_op.drop_index(batch_op.f('ix_payments_invoice_id'))

    op.drop_table('payments')
    with op.batch_alter_table('outbox', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outbox_status'))
        batch_op.drop_index(batch_op.f('ix_outbox_org_id'))
        batch_op.drop_index(batch_op.f('ix_outbox_invoice_id'))

    op.drop_table('outbox')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_org_id'))
        batch_op.drop_index(batch_op.f('ix_events_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_events_at'))

    op.drop_table('events')
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_tokens_purpose'))
        batch_op.drop_index(batch_op.f('ix_tokens_org_id'))

    op.drop_table('tokens')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_token_hash'))

    op.drop_table('sessions')
    with op.batch_alter_table('policy_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_settings_org_id'))

    op.drop_table('policy_settings')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_status'))
        batch_op.drop_index(batch_op.f('ix_invoices_org_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_next_action_on'))
        batch_op.drop_index(batch_op.f('ix_invoices_due_on'))
        batch_op.drop_index(batch_op.f('ix_invoices_customer_id'))

    op.drop_table('invoices')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_org_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('run_locks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_locks_org_id'))

    op.drop_table('run_locks')
    with op.batch_alter_table('risk_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_models_org_id'))
        batch_op.drop_index(batch_op.f('ix_risk_models_fitted_at'))
        batch_op.drop_index(batch_op.f('ix_risk_models_active'))

    op.drop_table('risk_models')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_org_id'))

    op.drop_table('customers')
    with op.batch_alter_table('audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_seq'))
        batch_op.drop_index(batch_op.f('ix_audit_org_id'))
        batch_op.drop_index(batch_op.f('ix_audit_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_audit_event'))
        batch_op.drop_index(batch_op.f('ix_audit_at'))

    op.drop_table('audit')
    with op.batch_alter_table('orgs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orgs_slug'))

    op.drop_table('orgs')
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_attempts_key'))
        batch_op.drop_index(batch_op.f('ix_login_attempts_at'))

    op.drop_table('login_attempts')
    # ### end Alembic commands ###
